name: 'Build and Sign Android'
description: 'Build and Sign Android apk'
runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup Android build environment
      uses: android-actions/setup-android@v3.2.0

    - name: Grant execute permission for gradlew
      run: chmod +x ./android/gradlew

    - name: Update AndroidManifest.xml
      uses: damienaicheh/update-android-version-manifest-action@v1.0.0
      with:
        android-manifest-path: './android/app/src/main/AndroidManifest.xml'
        version-code: ${{ env.NUMBER_OF_COMMITS }}
        version-name: '${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}'
        print-file: true

    - name: Update gradle version for Android
      uses: damienaicheh/update-android-version-gradle-action@v1.0.0
      with:
        build-gradle-path: './android/app/build.gradle'
        version-code: ${{ env.NUMBER_OF_COMMITS }}
        version-name: '${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}'
        print-file: true

    - name: Build app bundle
      working-directory: android
      run: ./gradlew clean app:assembleRelease
