name: Build for All platforms
on:
  push:
    tags:
      - 'v*.*.*'
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            extension: appimage
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.*

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.1.0

      - name: Install app dependencies
        run: npm install

      - name: Update package.json files
        run: node cli/update_version.js '${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}'

      - name: Build Minotaur JS app and update capacitor
        run: CI=false npm run sync

      - name: Build Electron
        working-directory: ./electron
        run: CI=false; npm i; npm run build; npm run electron:pack; npm run electron:make

      - name: Upload Executable File to release
        uses: softprops/action-gh-release@v1
        with:
          files: electron/dist/minotaur-wallet*.${{ matrix.extension }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')

