name: Build for All platforms
on:
  push:
    tags:
      - 'v*.*.*'
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
env:
  CI: false
jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            extension: AppImage
          - os: macos-latest
            platform: macOS
            extension: dmg
          - os: windows-latest
            platform: Windows
            extension: msi
          - os: ubuntu-latest
            platform: android
            extension: apk
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.*

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Setup Java
        if: matrix.platform == 'android'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Android build environment
        if: matrix.platform == 'android'
        uses: android-actions/setup-android@v3.2.0

      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.1.0

      - name: Install app dependencies
        run: npm install

      - name: Update package.json files
        run: node cli/update_version.js '${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}'

      - name: Build Minotaur JS app and update capacitor
        run: npm run sync
      
      - name: Remove icns from assets
        if: matrix.os != 'macos-latest'
        run: rm electron/assets/appIcon.icns

      - name: Build Android
        if: matrix.platform == 'android'
        uses: ./.github/actions/build-android

      - name: Build Electron
        if: matrix.platform != 'android'
        working-directory: ./electron
        run: npm i; npm run build; npm run electron:pack; npm run electron:make

      - name: Upload Executable File to release
        if: matrix.platform != 'android'
        uses: softprops/action-gh-release@v1
        with:
          files: electron/dist/minotaur-*.${{ matrix.extension }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')

