name: Build for All platforms
on:
  push:
    tags:
      - 'v*.*.*'
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
env:
  CI: false

jobs:
  build: 
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.*

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.1.0

      - name: Install app dependencies
        run: npm install

      - name: Update package.json files
        run: node cli/update_version.js '${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}'

      - name: Build Minotaur JS app and update capacitor
        run: npm run sync

  android:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Android build environment
        uses: android-actions/setup-android@v3.2.0

      - name: Grant execute permission for gradlew
        run: chmod +x ./android/gradlew

      - name: Update AndroidManifest.xml
        uses: damienaicheh/update-android-version-manifest-action@v1.0.0
        with:
          android-manifest-path: './android/app/src/main/AndroidManifest.xml'
          version-code: ${{ env.NUMBER_OF_COMMITS }}
          version-name: '${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}'
          print-file: true

      - name: Update gradle version for Android
        uses: damienaicheh/update-android-version-gradle-action@v1.0.0
        with:
          build-gradle-path: './android/app/build.gradle'
          version-code: ${{ env.NUMBER_OF_COMMITS }}
          version-name: '${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}'
          print-file: true

      - name: Build app bundle
        working-directory: android
        run: ./gradlew clean app:assembleRelease

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEYSTORE }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: move apk to root directory
        run: mv ${{steps.sign_app.outputs.signedReleaseFile}} minotaur-wallet-${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}.apk

      - name: Upload Apk File to release
        uses: softprops/action-gh-release@v1
        with:
          files: minotaur-wallet-*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  desktop:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            extension: AppImage
          - os: macos-latest
            platform: macOS
            extension: dmg
          - os: windows-latest
            platform: Windows
            extension: msi
    runs-on: ${{ matrix.os }}
    needs: build
    steps:
      - name: Remove icns from assets
        if: matrix.os != 'macos-latest'
        run: rm electron/assets/appIcon.icns

      - name: Build Electron
        if: matrix.platform != 'android'
        working-directory: ./electron
        run: npm i; npm run build; npm run electron:pack; npm run electron:make
      
      - name: Rename Executable File
        run: mv electron/dist/minotaur-*.${{ matrix.extension }} ./minotaur2-${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}.${{ matrix.extension }}

      - name: Upload Executable File to release
        uses: softprops/action-gh-release@v1
        with:
          files: minotaur2*.${{ matrix.extension }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

